---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
reg_dat <- read.csv("./input/database_overview_table_aggregated.csv")

colnames(reg_dat) <- c("insecticide", "countries_approved", "approved_crop_applications")

reg_dat$insecticide <- as.factor(reg_dat$insecticide)
```

```{r}
library(ggplot2)

p_country <- ggplot(data = reg_dat, aes(x = insecticide, y = countries_approved, fill = insecticide, color = insecticide)) + 
  
  geom_bar(stat="identity", width = 0.5) +
  
  theme(panel.background = element_blank()) +
  
  geom_text(aes(label = countries_approved), vjust = -0.5, size = 4) +
  
  scale_fill_brewer(palette = "Dark2") + 
  
  scale_color_brewer(palette = "Dark2") +
  
  theme(axis.title.x = element_blank()) +
  
  theme(legend.position = "none") +
  
  theme(axis.line.y = element_line(color="black")) +
  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 10), breaks = seq(0, 10, 2)) +
  
  theme(axis.text.x = element_text(size = 18, color = "black")) +
  
  theme(axis.text.y = element_text(size = 18, color = "black")) +
  
  theme(axis.title.y = element_text(size = 18, color = "black")) +
  
  ylab("Countries Approved In") +
  
  theme(axis.ticks.x = element_blank()) +
  
  ggtitle("Countries Approved In Without Restrictions") +
  
  theme(plot.title = element_text(size = 22, hjust = 0.5, face = "bold"))

p_country
```

``` {r}
cairo_pdf(file = "./country_barplot.pdf",   # The directory you want to save the file in
  width = 8, # The width of the plot in inches
  height = 6) # The height of the plot in inches

p_country

 dev.off()
```

```{r}
p_crop <- ggplot(data = reg_dat, aes(x = insecticide, y = approved_crop_applications, fill = insecticide, color = insecticide)) + 
  
  geom_bar(stat="identity", width = 0.5) +
  
  theme(panel.background = element_blank()) +
  
  geom_text(aes(label = approved_crop_applications), vjust = -0.3, size = 3.5) +
  
  scale_fill_brewer(palette = "Dark2") + 
  
  scale_color_brewer(palette = "Dark2") +
  
  theme(axis.title.x = element_blank()) +
  
  theme(legend.position = "none") +
  
  theme(axis.line.y = element_line(color="black")) +
  
  scale_y_continuous(expand = c(0, 0), limits = c(0, 80), breaks = seq(0, 80, 10)) +
  
  theme(axis.text.x = element_text(size = 10, color = "black")) +
  
  theme(axis.text.y = element_text(size = 10, color = "black")) +
  
  ylab("Approved Crop Applications") +
  
  theme(axis.ticks.x = element_blank()) +
  
  ggtitle("Crops Approved In Without Restrictions") +
  
  theme(plot.title = element_text(size = 14, hjust = 0.5, face="bold"))

p_crop
```

```{r}
cairo_pdf(file = "./crop_barplot.pdf",   # The directory you want to save the file in
  width = 8, # The width of the plot in inches
  height = 6) # The height of the plot in inches

p_crop

 dev.off()
```


